[global]
username = "einfachnur.alex"
password_cmd = "/usr/bin/pass spotify.com/aleksej.chaichan@posteo.de"
backend = "alsa"
mixer = "PCM"
volume_controller = "softvol"
device_name = "spotify"
bitrate = 160
cache_path = "/home/alex/.cache/spotifyd"
volume_normalisation = true
zeroconf_port = 1234
